name: Build
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build_linux:
        name: Build (Linux)
        runs-on: ubuntu-latest
        steps:
            - name: Install Rust Toolchain
              run: |
                  rustup update --no-self-update stable
                  rustup component add --toolchain stable rustfmt rust-src
                  rustup default stable
            - name: Check out Source Code
              uses: actions/checkout@v4
              with:
                  submodules: 'true'
            - name: Build
              run: cargo build
            - name: Test
              run: cargo test
    build_windows:
        name: Build (Windows)
        runs-on: windows-latest
        steps:
            - name: Install Rust Toolchain
              run: |
                  rustup update --no-self-update stable
                  rustup component add --toolchain stable rustfmt rust-src
                  rustup default stable
            - name: Check out Source Code
              uses: actions/checkout@v4
              with:
                  submodules: 'true'
            - name: Build
              run: cargo build
            - name: Test
              run: cargo test
    build_macos:
        name: Build (MacOS)
        runs-on: macos-latest
        steps:
            - name: Install Rust Toolchain
              run: |
                  rustup update --no-self-update stable
                  rustup component add --toolchain stable rustfmt rust-src
                  rustup default stable
            - name: Check out Source Code
              uses: actions/checkout@v4
              with:
                  submodules: 'true'
            - name: Build
              run: cargo build
            - name: Test
              run: cargo test
