name: Build (Linux)
on:
    push:
        branches:
            - main
jobs:
    cargo_build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Rust
              run: |
                rustup update --no-self-update stable
                rustup component add --toolchain stable rustfmt rust-src
                rustup default stable
            - name: Check out Source Code
              uses: actions/checkout@v4
            - name: Build
              run: cargo build
            - name: Test
              run: cargo test
